ExpenseBuddy.Web/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using ExpenseBuddy.Data.Models;
using ExpenseBuddy.Services;
using ExpenseBuddy.Services.BankAccounts;
using ExpenseBuddy.Web.Models.BankAccountsViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExpenseBuddy.Web.Controllers
{
    public class BankAccountsController : BaseController
    {
        private readonly IBankAccountRepositoryService _bankAccounts;
        private readonly IBankRepositoryService _banks;
        private readonly IApplicationUserRepositoryService _users;
        private readonly IUserBankAccountService _bankUserAccountsService;
        private readonly UserManager<ApplicationUser> _um;

        public BankAccountsController(
            IBankAccountRepositoryService bankAccounts,
            IBankRepositoryService banks,
            IApplicationUserRepositoryService users,
            IUserBankAccountService bankUserAccountsService,
            UserManager<ApplicationUser> um)
        {
            _bankAccounts = bankAccounts;
            _banks = banks;
            _users = users;
            _bankUserAccountsService = bankUserAccountsService;
            _um = um;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _um.FindByNameAsync(User.Identity.Name);

            if (await _um.IsInRoleAsync(user, "Administrator"))
            {
                var ba = await _bankUserAccountsService.All();
                return View(ba);
            }
            else
            {
                var ba = await _bankUserAccountsService.AllForUser(user.Id);
                return View(ba);
            }

        }

        public IActionResult Create()
        {

            var ba = new BankAccountCreateViewModel()
            {
                IsActive = true,
                Banks = _bankUserAccountsService.GetBanksList()
            };

            return View(ba);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BankAccountCreateViewModel bankAccount)
        {
            if (!ModelState.IsValid)
            {
                bankAccount.Banks = _bankUserAccountsService.GetBanksList();

                return View(bankAccount);
            }

            try
            {
                var user = (await _users.AllAsync(predicate: k => k.UserName == User.Identity.Name)).FirstOrDefault();

                var ba = Mapper.Map(bankAccount, new BankAccount(), opt => opt.AfterMap((src, dst) => dst.UserId = user.Id));

                await _bankUserAccountsService.Create(ba);
            }
            catch (Exception e) {

                ModelState.AddModelError("", e.Message);

                bankAccount.Banks = _bankUserAccountsService.GetBanksList();

                return View(bankAccount);
            }

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Edit(int id)
        {
            var b = (await _bankAccounts.AllAsync<BankAccountEditViewModel>(predicate: k => k.Id == id)).FirstOrDefault();

            b.Banks = _bankUserAccountsService.GetBanksList();


            return View(b);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BankAccountEditViewModel bankAccount)
        {
            if (!ModelState.IsValid)
            {
                bankAccount.Banks = _bankUserAccountsService.GetBanksList();
                return View(bankAccount);
            }

            try
            {

                var b = (await _bankAccounts.AllAsync(predicate: k => k.Id == bankAccount.Id)).FirstOrDefault();

                if (b == null)
                {
                    return NotFound();
                }

                Mapper.Map(bankAccount, b);

                await _bankAccounts.SaveChangesAsync();

            }
            catch (Exception e) {

                ModelState.AddModelError("", e.Message);

                bankAccount.Banks = _bankUserAccountsService.GetBanksList();

                return View(bankAccount);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddFunds(int id)
        {
            var ba = await _bankUserAccountsService.FindById(id);

            var afba = Mapper.Map(ba, new BankAccountAddFundsViewModel());

            return View(afba);
        }

        [HttpPost]
        public async Task<IActionResult> AddFunds(int id, BankAccountAddFundsViewModel funds)
        {

            if (!ModelState.IsValid) {
                return View(funds);
            }

            try
            {

                var ba = await _bankUserAccountsService.FindById(id);

                var user = await _um.FindByNameAsync(User.Identity.Name);

                await _bankUserAccountsService.AddFunds(user.Id, ba.UserId, ba.Number, funds.AddAmount);

            }
            catch (Exception e) {
                ModelState.AddModelError("", e.Message);
                return View(funds);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ExpenseBuddy.Web/Controllers/DutiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExpenseBuddy.Data.Models;
using ExpenseBuddy.Services.Duties;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseBuddy.Web.Controllers
{
    public class DutiesController : BaseController
    {
        private readonly IDutiesService _duties;
        private readonly UserManager<ApplicationUser> _userManager;
        private ApplicationUser _user;

        public DutiesController(
            IDutiesService duties,
            UserManager<ApplicationUser> userManager)
        {
            _duties = duties;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {

            if (User.IsInRole("Administrator"))
            {
                var tmp = await _duties.All();
                return View(tmp);
            }
            else
            {
                _user = await _userManager.FindByNameAsync(User.Identity.Name);
                var tmp = await _duties.AllForUser(_user.Id);
                return View(tmp);
            }
        }

        public async Task<IActionResult> Pay(int expenseId, string payerId)
        {
            _user = await _userManager.FindByNameAsync(User.Identity.Name);
            var du = await _duties.FindById(_user.Id, expenseId, payerId);

            return View(du);
        }

        [HttpPost]
        public async Task<IActionResult> Pay(string payerId, int expenseId)
        {
            _user = await _userManager.FindByNameAsync(User.Identity.Name);

            var du = await _duties.FindById(_user.Id, expenseId, payerId);

            try
            {
                await _duties.Pay(_user.Id, expenseId, payerId);
            }
            catch (Exception e) {
                ModelState.AddModelError("", e.Message);
                return View(du);
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

ExpenseBuddy.Web/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExpenseBuddy.Data;
using ExpenseBuddy.Data.Models;
using ExpenseBuddy.Web.Models.ExpensesViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoMapper.QueryableExtensions;
using AutoMapper;
using ExpenseBuddy.Services.Expenses;
using ExpenseBuddy.Common.Infrastructure;

namespace ExpenseBuddy.Web.Controllers
{
    public class ExpensesController : BaseController
    {
        private readonly ExpenseBuddyDbContext _ctx;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IExpenseService _expService;

        public ExpensesController(
            ExpenseBuddyDbContext ctx,
            UserManager<ApplicationUser> userManager,
            IExpenseService expService)
        {
            _ctx = ctx;
            _userManager = userManager;
            _expService = expService;
        }

        public async Task<IActionResult> Index(int? page, string search, string opt)
        {
            //var exp = await _expService.All();

            if (opt == "clear-filter")
            {
                ViewData["filter"] = "";
                search = "";
                return RedirectToAction(nameof(Index));
            }
            else {
                ViewData["filter"] = search;
            }

            var expPaged = await _expService.AllPaginated<Expense>(search, page, 3);

            //PaginatedList<ExpenseListingViewModel> items = new PaginatedList<ExpenseListingViewModel>();

            //var expVm = Mapper.Map(expPaged, items);

            return View(expPaged);
        }

        public async Task<IActionResult> Create()
        {

            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var p = await _expService.GetPayersList(0, user.Id);
            var o = _expService.GetOwnersList(user.Id);
            var e = await _expService.GetElementsList();

            var m = new ExpenseCreateViewModel()
            {
                Elements = e,
                Owners = o,
                Payers = p.ToList(),
                ExpenseDate = DateTime.Now
            };

            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ExpenseCreateViewModel expense)
        {
            if (!ModelState.IsValid)
            {
                return View(expense);
            }

            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var selectedPayers = expense
                .Payers
                .Where(k => k.Selected)
                .Select(k => k.Value);

            if (selectedPayers.Count() == 0)
            {

                ModelState.AddModelError("", "You must select at least one Payer!");

                var p = await _expService.GetPayersList(0, user.Id);
                var o = _expService.GetOwnersList("");
                var e = await _expService.GetElementsList();

                expense.Payers = p.ToList();
                expense.Owners = o;
                expense.Elements = e;

                return View(expense);

            }

            var ex = Mapper.Map(expense, new Expense());

            await _expService.CreateAsync(ex, expense.Payers);


            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {

            var ex = await _expService.FindById(id);

            if (ex == null) {
                return NotFound();
            }

            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var o = _expService.GetOwnersList(ex.OwnerId);
            var p = await _expService.GetPayersList(ex.Id, user.Id);
            var e = await _expService.GetElementsList();

            var m = Mapper
                .Map(ex, new ExpenseEditViewModel() { }, opt 
                    => opt.BeforeMap((s, d) => 
                    {
                        d.Elements = e;
                        d.Payers = p.ToList();
                        d.Owners = o;
                    }));

            return View(m);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, ExpenseEditViewModel expense)
        {

            if (!ModelState.IsValid)
            {
                return View(expense);
            }

            var selectedPayers = expense
                .Payers
                .Where(k => k.Selected)
                .Select(k => k.Value);

            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            if (selectedPayers.Count() == 0)
            {
                var o = _expService.GetOwnersList(expense.OwnerId);
                var p = await _expService.GetPayersList(expense.Id, user.Id);
                var e = await _expService.GetElementsList();

                expense.Owners = o;
                expense.Payers = p.ToList();
                expense.Elements = e;

                ModelState.AddModelError("", "You must select at least one Payer!");
                return View(expense);
            }


            var expUpdated = Mapper.Map(expense, new Expense());

            try
            {
                await _expService.Update(id, expUpdated, expense.Payers);
            }
            catch (Exception exeption) {
                var o = _expService.GetOwnersList(expense.OwnerId);
                var p = await _expService.GetPayersList(expense.Id, user.Id);
                var e = await _expService.GetElementsList();

                expense.Owners = o;
                expense.Payers = p.ToList();
                expense.Elements = e;

                ModelState.AddModelError("", exeption.Message);
                return View(expense);
            }


            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var ex = await _ctx
                .Expenses
                .Include(k => k.Payers)
                    .ThenInclude(p => p.Payer)
                .Include(k => k.Owner)
                .Include(k => k.Element)
                .FirstOrDefaultAsync(k => k.Id == id);

            if (ex == null)
            {
                return NotFound();
            }

            return View(ex);
        }

    }
}

ExpenseBuddy.Web/Views/Shared/_ExpensePartial.cshtml
@model ExpenseBuddy.Data.Models.Expense

@{
    ViewData["Title"] = "Details";
}

<h2>Expense details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExpenseDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExpenseDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Shop)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Shop)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fee)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reference)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reference)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Element)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Element.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Owner.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Payers)
        </dt>
        <dd>
            @Html.Partial("_ExpensePayersPartial", Model.Payers)
        </dd>
    </dl>
</div>

ExpenseBuddy.Web/Views/Shared/_ExpensePayersPartial.cshtml
@model IEnumerable<ExpenseBuddy.Data.Models.ExpensePayer>

@foreach (var payer in Model)
{
    <div class="row" style="font-family: Consolas">
        <div class="col-md-12">
            @if (payer.Status == PaymentStatus.Payed)
            {
                <div style="text-decoration: line-through; color: silver">
                    @string.Format("{0:F3} BGN", payer.Amount) - @payer.Payer?.UserName
                </div>
            }
            else
            {
                <div>@string.Format("{0:F3} BGN", payer.Amount) - @payer.Payer?.UserName</div>
            }
        </div>
    </div>
}

ExpenseBuddy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseBuddy.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ExpenseBuddy</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a></li>
                    <li><a asp-area="" asp-controller="Duties" asp-action="Index">Duties</a></li>
                    <li><a asp-area="" asp-controller="BankAccounts" asp-action="Index">Bank Accounts</a></li>
                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ExpenseBuddy.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>